# Resolve all *.home-server to this machine
address=/home-server/100.126.155.105

# Listen only on Tailscale IP
listen-address=100.126.155.105
bind-interfaces

# Standard DNS port
port=53

# Don't use /etc/hosts
no-hosts

# Don't forward unresolved queries  
bogus-priv
